apiVersion: 1
groups:
    - orgId: 1
      name: defoult
      folder: todoList
      interval: 5m
      rules:
        - uid: efdx5dg1m3jlsc
          title: Backend 5xx rate
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "100 *\r\n(\r\n  sum(rate(http_requests_total{handler!~\"/(openapi.json|health|metrics)\", status=~\"5..\"}[5m]))\r\n/ \r\n  sum(rate(http_requests_total{handler!~\"/(openapi.json|health|metrics)\"}[5m])))\r\n> 3\r\nand\r\nsum(rate(http_requests_total{handler!~\"/(openapi.json|health|metrics)\"}[5m])) > 0.2"
                instant: true
                interval: ""
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: OK
          for: 5m
          annotations:
            description: Backend 5xx rate > 3% for 5 minutes
            summary: Backend 5xx rate > 3% for 5 minutes
          isPaused: false
          notification_settings:
            receiver: telega
        - uid: efdxaeytx2ccge
          title: slowly latency
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  )\r\n)"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 5m
          annotations:
            description: где то хваост
          isPaused: false
          notification_settings:
            receiver: telega
        - uid: ffdxc8fim5ptsd
          title: 'memory over '
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "100 *\r\nsum by (container_label_com_docker_compose_service) (\r\n  container_memory_working_set_bytes{container_label_com_docker_compose_service=~\"backend_one|backend_two\"}\r\n)\r\n/\r\nsum by (container_label_com_docker_compose_service) (\r\n  container_spec_memory_limit_bytes{container_label_com_docker_compose_service=~\"backend_one|backend_two\"}\r\n)"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 5m
          annotations:
            description: работа на пределе ram
          isPaused: false
          notification_settings:
            receiver: telega
        - uid: dfdxdiecgim0wd
          title: queue upper
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "( rabbitmq_queue_messages_ready{queue=\"tasks\"} > bool 100 )\r\nand\r\n( delta(rabbitmq_queue_messages_ready{queue=\"tasks\"}[10m]) > bool 0 )"
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: reducer
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: reducer
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: reducer
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 5m
          annotations:
            summary: чекай очередь
          isPaused: false
          notification_settings:
            receiver: telega
        - uid: dfdxfgd9tdfcwc
          title: Postgres connections
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "100 *\r\nsum(pg_stat_activity_count)\r\n/\r\nmax(pg_settings_max_connections)"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 5m
          isPaused: false
          notification_settings:
            receiver: telega
