{
 "title": " API OverView",
 "tags": [
  "metrics",
  "backend",
  "api"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(http_requests_total,app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le, handler) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (le, handler, method) (\r\n  rate(http_requests_total\r\n  {app_name=\"$app_name\", handler!~\"^/(health|metrics)$\"}[1m]\r\n  )\r\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, handler) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\r\n  sum by (le, handler) (\r\n    rate(http_request_duration_seconds_bucket[5m])\r\n  ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 * (\r\n  sum(rate(http_requests_total{status=~\"5..\", handler!~\"^/(health|metrics)$\"}[1m]))\r\n/\r\n  sum(rate(http_requests_total{handler!~\"^/(health|metrics)$\"}[1m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API CPU %",
   "type": "gauge",
   "description": "0.1 = 0.1% одного ядра",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (name) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    name=~\"^(backend_one|backend_two)$\"\r\n    }[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "backend RAM mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\r\n  container_memory_working_set_bytes{container_label_com_docker_compose_service=~\"(backend_one|backend_two)\"} / 1024 /1024\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Новая панель",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=~\".*/(b345285844567e306db62d6f2fbc40e6b56bcab21699df1c9365f80adf9e7493|edba4d9acb258fd89bfdee76461f6e2527d2123389357a2f3be90d8fa9498329).*\"} | json | line_format \"{{.log}}\""
    }
   ]
  }
 ]
}