{
 "title": "Celery Tasks",
 "description": "A dashboard that monitors Celery. It is created using the Celery-mixin for the the (Celery-exporter)[https://github.com/danihodovic/celery-exporter].",
 "tags": [
  "celery",
  "queue"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(celery_worker_up{}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(celery_worker_up{namespace=\"$namespace\"}, job)"
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": "label_values(celery_task_received_total{namespace=\"$namespace\", job=\"$job\", name!~\"None\"}, queue_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue State",
   "type": "timeseries",
   "description": "для отличия роста тасков от вставших воркеров",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_queue_messages{queue=\"tasks\"})",
     "legendFormat": "total tasks"
    },
    {
     "expr": "sum by (queue) (rabbitmq_queue_messages_ready{queue=\"tasks\"})",
     "legendFormat": "ready tasks"
    },
    {
     "expr": "sum by (queue) (rabbitmq_queue_messages_unacknowledged{queue=\"tasks\"})",
     "legendFormat": "processing without ACT"
    }
   ]
  },
  {
   "title": "worker RAM mb",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (container_memory_usage_bytes{container_label_com_docker_compose_service=\"celery_worker\"} / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "worker CPU %",
   "type": "timeseries",
   "description": "0.250 ~ 0.25% одного ядра",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "100 *\r\nsum by (container_label_com_docker_compose_service) (\r\n    rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"celery_worker\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}