{
 "title": "RabbitMQ",
 "description": "Tested with latest prometheus exporter, 2019-09",
 "tags": [ "queue" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(rabbitmq_channelsTotal, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(rabbitmq_channelsTotal, pod)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(rabbitmq_channelsTotal, namespace)"
   },
   {
    "name": "queue",
    "label": "queue",
    "query": "label_values(rabbitmq_queue_messages_get_total, queue)"
   },
   {
    "name": "vhost",
    "label": "vhost",
    "query": "label_values(rabbitmq_queue_messages_get_total, vhost)"
   }
  ]
 },
 "panels": [
  {
   "title": "MSGS PUB by $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_exchange_messages_published_in_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_exchange_messages_published_in_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "MSGS SUBS by $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_exchange_messages_published_out_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_exchange_messages_published_out_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_node_mem_used{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_node_mem_used{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Used Memory by Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ram{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_messages_ram{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Queue Size (Bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_message_bytes{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_message_bytes{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue, vhost, pod) (increase(rabbitmq_queue_messages[1m])) / ignoring (queue, vhost, pod) group_left count(rabbitmq_queue_messages)",
     "legendFormat": "[{{pod}}]-[{{queue}}]"
    }
   ]
  },
  {
   "title": "Messages Overview",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_ready{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_ready{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[READY] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_published_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_published_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[PUBLISHED] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_delivered_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_delivered_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[DELIVERED] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_delivered_noack_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_delivered_noack_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[NOACK] {{queue}}"
    }
   ]
  },
  {
   "title": "ACK Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_ack_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_ack_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Delivered Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_delivered_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_delivered_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Returned Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_returned_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_returned_total{queue=~\"$queue\", service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", vhost=~\"$vhost\"})",
     "legendFormat": "{{ queue }}"
    }
   ]
  }
 ]
}