"""login/registr

Revision ID: 098d3c75d3b4
Revises: b3c7df417b96
Create Date: 2026-01-02 11:08:53.299273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098d3c75d3b4'
down_revision: Union[str, Sequence[str], None] = 'b3c7df417b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password_hashed", new_column_name="hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", new_column_name="password_hashed")
    # ### end Alembic commands ###
