"""correct [celery]

Revision ID: 176739e1745c
Revises: d9f9de876411
Create Date: 2026-01-27 23:58:49.696429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176739e1745c'
down_revision: Union[str, Sequence[str], None] = 'd9f9de876411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('message_reminder', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'message_reminder')
    # ### end Alembic commands ###
