"""add_column_last_reminder_id

Revision ID: 50b13f74ffc9
Revises: 98e064859cd6
Create Date: 2026-01-24 16:48:46.974101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b13f74ffc9'
down_revision: Union[str, Sequence[str], None] = '98e064859cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_reminder_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_reminder_id')
    # ### end Alembic commands ###
