"""completed_task_model

Revision ID: b3c7df417b96
Revises: 97de1fad4ef3
Create Date: 2025-12-21 16:14:52.132702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c7df417b96'
down_revision: Union[str, Sequence[str], None] = '97de1fad4ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('reminder_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index('ix_tasks_user_completed', 'tasks', ['user_id', 'is_completed'], unique=False)
    # op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index('ix_tasks_user_completed', table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'reminder_time')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'is_completed')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    # ### end Alembic commands ###
