"""update_notifications_schema_message_read_at

Revision ID: d9f9de876411
Revises: 50b13f74ffc9
Create Date: 2026-01-25 21:58:02.153208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9f9de876411'
down_revision: Union[str, Sequence[str], None] = '50b13f74ffc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('message', sa.Text(), nullable=False))
    op.drop_column('notifications', 'payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'read_at')
    # ### end Alembic commands ###
