name: CI

on:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        py: [ "3.11", "3.13" ]

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: app_db
          POSTGRES_USER: app
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app -d app_db"
          --health-interval=5s 
          --health-timeout=5s 
          --health-retries=10
    env:
      DATABASE_URL_ASYNC_INNER: postgresql+asyncpg://app:pass@database:5432/app_db
      DATABASE_URL_SYNC_OUT: postgresql+psycopg://app:pass@localhost:5432/app_db
      DATABASE_URL_SYNC_INNER: postgresql+psycopg://app:pass@database:5432/app_db
      DATABASE_URL_ASYNC_OUT: postgresql+asyncpg://app:pass@localhost:5432/app_db
      CELERY_BROKER_URL: amqp://app:pass@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SECRET_KEY: change_me
      ACCESS_TOKEN_EXPIRE_MINUTES: 60


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{matrix.py}}"

      - name: Install deps
        run: | 
          python -m pip install -U pip
          pip install . pytest pytest-asyncio httpx

      - name: Migrations
        run: |
          alembic -x env=out upgrade head

      - name: Tests
        run: pytest -q

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install flake8
        run: pip install flake8

      - name: Run linter
        run: flake8 .